[build]
  command = "npm install && npm run build"
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--production=false"
  PHP_VERSION = "8.1"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
